# -*- coding: utf-8 -*-
"""Python_workingwith_datatypes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11D_AAAAWespTf47AyReYPUf48L-YNGan
"""

"""
Developer Name: Mandela Thomas
Developer Email: mthomas232@atsmas.com
Developer Website: www.atsmas.com
Developer Github: https://github.com/mandelathomas
Developer Linkedin:https://www.linkedin.com/in/mandela-philip-thomas/
Project Date : July 30, 2026
Project Name : Basic Python
Project Description : Using python to learn basic concepts

"""


#import various libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
import datetime
import collections

#---working with list ----

#two groups
cousins = ['Paul ', 'James', 'Tom', 'Peter']
payment = [200, 400, 100, 150]

#the total values in the list
print(len(cousins))

#the first [1] and last [-1]person in the group
print(f'{cousins[0]}is the first on the ticket list')
print(f'{cousins[-1]} is the last on theticket list')

#join both  list
paylist = cousins, payment
print(paylist)

#combine multiple iterables into a single iterator of tuples
paylist = list(zip(cousins, payment))
print(paylist)

#verifying if james is part of the group
if 'james' in cousins:
  print("James is in the group")
else:
  print("James is not in the group")

  #add a single new person and payments to the group
  cousins.append('Mandela ')
  payment.append(800)

  print(cousins, payment )

#add mutiple people and payments to the group

cousins.extend(['Kollie', 'Ben'])
payment.extend([600,350])

print(cousins, payment)

#Add a new cousin and their payment to your lists at a specific position

cousins.insert(2, 'Mary')
payment.insert(2, 270)

print(cousins, payment)

#delete a person and payment from the group
del cousins[0]
del payment [0]

cousins.remove('Mary')
payment.remove(270)
print(cousins, payment)


#arrange the group
cousins.sort()
payment.sort()

#pick the first and last people on the group
cousins[-1:]

#add two new people to the group
cousins[1:2] =['Pauline', 'Miracle']

#delete people from the group
del cousins[1:2]
print(cousins)

for participants in cousins:
  print(participants)



for i in range(len(cousins)):
  print(cousins[i])